*** Variables ***
${ALLOW CAMERA ACCESS}      	com.playgroundxyz.vision_project:id/confirmButton
${ALLOW ScreenRecording}      	com.playgroundxyz.vision_project:id/confirmButton
${TrackYourGazeDeclineBtn}          com.playgroundxyz.vision_project:id/declineButton
${Allow While using the app}        com.android.permissioncontroller:id/permission_allow_foreground_only_button
${Allow onlyThisTime}        com.android.permissioncontroller:id/permission_allow_one_time_button
${Deny permission}      	com.android.permissioncontroller:id/permission_deny_button
${continueBtn}          com.playgroundxyz.vision_project:id/confirmButton
${startNowBtn}          	android:id/alertTitle
