*** Variables ***
${EyeGazeValiidation titleText}        Look at the dot until it goes green and disappears
${EyeGazeValiidation BeginBtn}         com.playgroundxyz.vision_project:id/beginButton
${EyeGazeValiidation ContinueToAccuracyCheckBtn}         com.playgroundxyz.vision_project:id/beginButton
${ViewAQuickDemoBtn}        com.playgroundxyz.vision_project:id/demoButton
${Skip&StartTheStudyBtn}       	com.playgroundxyz.vision_project:id/startTextview
${studyInstructions StartStudyBtn}      	com.playgroundxyz.vision_project:id/beginButton
${studyInstructions RecordingPausedIcon}      	Study demo
${tryAgainBtn}          	com.playgroundxyz.vision_project:id/tryButton
${AccuracyNeedsToBeImproved NeedHelpBtn}        com.playgroundxyz.vision_project:id/fragmentValidationFailNeedHelpButton