*** Variables ***
${LetsSetupYourEyeTrackingPage title}       	    com.playgroundxyz.vision_project:id/title
${LetsSetupYourEyeTrackingPage checkBox1}       	com.playgroundxyz.vision_project:id/check1
${LetsSetupYourEyeTrackingPage checkBox2}       	com.playgroundxyz.vision_project:id/check2
${LetsSetupYourEyeTrackingPage checkBox3}       	com.playgroundxyz.vision_project:id/check3
${LetsSetupYourEyeTrackingPage checkBox4}       	com.playgroundxyz.vision_project:id/check4
${LetsSetupYourEyeTrackingPage SetupBtn}        	com.playgroundxyz.vision_project:id/confirmButton

