*** Settings ***
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/Camera app locators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/Need Help page locators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/study page locators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/welcome Page Locators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/Allow permission page locators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/LetsSetupYourEyeTrackingLocators.resource
Resource        ../com.playgroundxyz.vision_project.PageObject.locators/EyeGazeValiidationpageLocators.resource
