*** Variables ***

#welcome page locators
${Study link textbox}       com.playgroundxyz.vision_project:id/studyLink
${Help icon}        com.playgroundxyz.vision_project:id/logo_help
${Welcome to the Vision Project}        com.playgroundxyz.vision_project:id/title
${Paste study link}         com.playgroundxyz.vision_project:id/pasteStudyLink
${GET STARTED}         	com.playgroundxyz.vision_project:id/beginButton