*** Variables ***

# AIP Locators
${QR_Code}      //*[@viewBox='0 0 256 256']
${camera_smartchip_text}        com.google.android.GoogleCamera:id/smarts_chip_text
${google_playstore_Button}      //android.widget.Button[@index=3]
${Open Study In app}        //android.view.View[@content-desc="OPEN STUDY IN APP"]/android.widget.Button
${Need_Help}        //android.view.View[@content-desc="Need Help"]/android.widget.TextView
