*** Variables ***
${EyeGazeValiidation titleText}        Look at the dot until it goes green and disappears
${EyeGazeValiidation BeginBtn}         com.playgroundxyz.vision_project:id/beginButton
${EyeGazeValiidation ContinueToAccuracyCheckBtn}         com.playgroundxyz.vision_project:id/beginButton
${ViewAQuickDemoBtn}        com.playgroundxyz.vision_project:id/demoButton
${Skip&StartTheStudyBtn}       	com.playgroundxyz.vision_project:id/startTextview
