*** Settings ***
Resource        ../XYZProject.PageObject.locators/Camera app locators.resource
Resource        ../XYZProject.PageObject.locators/Need Help page locators.resource
Resource        ../XYZProject.PageObject.locators/study page locators.resource
Resource        ../XYZProject.PageObject.locators/welcome Page Locators.resource
Resource        ../XYZProject.PageObject.locators/Allow permission page locators.resource
Resource        ../XYZProject.PageObject.locators/LetsSetupYourEyeTrackingLocators.resource
